### ISSUE TITLE
Failure to build: pygobject/3.18.2

### ISSUE THREAD

**Issue by davidedelvento** [NCAR/ncarcompilers#23]
@vanderwb can you please share the script that you used to attempt this build, to ease my duplication of the problem to try to debug it? Path on the super is fine, no need to scp, attach, etc. 

Also, google is not very clear where to download an official pygobject/3.18.2, so if you can share a URL (or, again, location of tarball on the machine, that would help too).

Thanks!

**Comment by benkirk** [comment]
closing old issue.
